import type { Quiz } from "../types";

export const quiz2Data: Quiz = {
  id: "quiz_tech_v1",
  title: "Tech & Innovation Challenge",
  description:
    "Test your knowledge of technology, programming, and digital innovation. From algorithms to hardware, this quiz covers the digital world!",
  questions: [
    {
      id: "q1",
      type: "mcq",
      subject: "Web Development",
      text: "What does 'HTML' stand for?",
      pointsCorrect: 10,
      pointsIncorrect: 3,
      options: [
        { id: "opt_a", text: "Hypertext Markup Language" },
        { id: "opt_b", text: "High Tech Modern Language" },
        { id: "opt_c", text: "Home Tool Markup Language" },
        { id: "opt_d", text: "Hyperlink and Text Markup Language" },
      ],
      correctOptionId: "opt_a",
    },
    {
      id: "q2",
      type: "numerical",
      subject: "Programming History",
      text: "In what year was JavaScript first released?",
      pointsCorrect: 15,
      pointsIncorrect: 8,
      correctAnswer: 1995,
    },
    {
      id: "q3",
      type: "mcq",
      subject: "Programming Languages",
      text: "Which company developed the Java programming language?",
      pointsCorrect: 10,
      pointsIncorrect: 5,
      options: [
        { id: "opt_a", text: "Microsoft" },
        { id: "opt_b", text: "Sun Microsystems" },
        { id: "opt_c", text: "Apple" },
        { id: "opt_d", text: "Google" },
      ],
      correctOptionId: "opt_b",
    },
    {
      id: "q4",
      type: "mcq",
      subject: "Artificial Intelligence",
      text: "What does 'AI' stand for in technology?",
      pointsCorrect: 5,
      pointsIncorrect: 2,
      options: [
        { id: "opt_a", text: "Automated Intelligence" },
        { id: "opt_b", text: "Artificial Intelligence" },
        { id: "opt_c", text: "Advanced Integration" },
        { id: "opt_d", text: "Application Interface" },
      ],
      correctOptionId: "opt_b",
    },
    {
      id: "q5",
      type: "numerical",
      subject: "Computer Science",
      text: "How many bits are in a byte?",
      pointsCorrect: 10,
      pointsIncorrect: 3,
      correctAnswer: 8,
    },
    {
      id: "q6",
      type: "mcq",
      subject: "Programming Languages",
      text: "Which of these is NOT a programming language?",
      pointsCorrect: 10,
      pointsIncorrect: 4,
      options: [
        { id: "opt_a", text: "Python" },
        { id: "opt_b", text: "JavaScript" },
        { id: "opt_c", text: "Photoshop" },
        { id: "opt_d", text: "Ruby" },
      ],
      correctOptionId: "opt_c",
    },
    {
      id: "q7",
      type: "mcq",
      subject: "Hardware",
      text: "What does 'CPU' stand for?",
      pointsCorrect: 8,
      pointsIncorrect: 3,
      options: [
        { id: "opt_a", text: "Computer Processing Unit" },
        { id: "opt_b", text: "Central Processing Unit" },
        { id: "opt_c", text: "Core Processing Unit" },
        { id: "opt_d", text: "Central Program Unit" },
      ],
      correctOptionId: "opt_b",
    },
    {
      id: "q8",
      type: "numerical",
      subject: "Computer Science",
      text: "How many megabytes (MB) are in 1 gigabyte (GB)?",
      pointsCorrect: 15,
      pointsIncorrect: 7,
      correctAnswer: 1024,
    },
    {
      id: "q9",
      type: "mcq",
      subject: "Tech Companies",
      text: "Which company created the iPhone?",
      pointsCorrect: 5,
      pointsIncorrect: 2,
      options: [
        { id: "opt_a", text: "Samsung" },
        { id: "opt_b", text: "Google" },
        { id: "opt_c", text: "Apple" },
        { id: "opt_d", text: "Microsoft" },
      ],
      correctOptionId: "opt_c",
    },
    {
      id: "q10",
      type: "mcq",
      subject: "Web Development",
      text: "What does 'URL' stand for?",
      pointsCorrect: 10,
      pointsIncorrect: 4,
      options: [
        { id: "opt_a", text: "Universal Resource Locator" },
        { id: "opt_b", text: "Uniform Resource Locator" },
        { id: "opt_c", text: "Universal Reference Link" },
        { id: "opt_d", text: "Uniform Reference Locator" },
      ],
      correctOptionId: "opt_b",
    },
    {
      id: "q11",
      type: "numerical",
      subject: "Computer Science",
      text: "In binary, what decimal number does '1010' represent?",
      pointsCorrect: 20,
      pointsIncorrect: 10,
      correctAnswer: 10,
    },
    {
      id: "q12",
      type: "mcq",
      subject: "Networking",
      text: "Which protocol is used to transfer web pages?",
      pointsCorrect: 12,
      pointsIncorrect: 6,
      options: [
        { id: "opt_a", text: "FTP" },
        { id: "opt_b", text: "SMTP" },
        { id: "opt_c", text: "HTTP" },
        { id: "opt_d", text: "SSH" },
      ],
      correctOptionId: "opt_c",
    },
    {
      id: "q13",
      type: "mcq",
      subject: "Tech History",
      text: "Who co-founded Microsoft with Bill Gates?",
      pointsCorrect: 15,
      pointsIncorrect: 8,
      options: [
        { id: "opt_a", text: "Steve Jobs" },
        { id: "opt_b", text: "Paul Allen" },
        { id: "opt_c", text: "Larry Page" },
        { id: "opt_d", text: "Mark Zuckerberg" },
      ],
      correctOptionId: "opt_b",
    },
    {
      id: "q14",
      type: "numerical",
      subject: "Computer Science",
      text: "What is the maximum value that can be stored in an 8-bit unsigned integer?",
      pointsCorrect: 18,
      pointsIncorrect: 9,
      correctAnswer: 255,
    },
    {
      id: "q15",
      type: "mcq",
      subject: "Databases",
      text: "Which database query language is most commonly used?",
      pointsCorrect: 10,
      pointsIncorrect: 5,
      options: [
        { id: "opt_a", text: "NoSQL" },
        { id: "opt_b", text: "SQL" },
        { id: "opt_c", text: "GraphQL" },
        { id: "opt_d", text: "XML" },
      ],
      correctOptionId: "opt_b",
    },
  ],
};
