import type { Quiz } from "../types";

export const quiz1Data: Quiz = {
  id: "quiz_main_v1",
  title: "The Ultimate Knowledge Challenge",
  description:
    "A fast-paced quiz with a mix of general knowledge and numerical brain teasers. Be warned: incorrect answers have penalties!",
  questions: [
    {
      id: "q1",
      type: "mcq",
      subject: "Geography",
      text: "What is the capital city of Canada?",
      pointsCorrect: 10,
      pointsIncorrect: 5,
      options: [
        { id: "opt_a", text: "Toronto" },
        { id: "opt_b", text: "Vancouver" },
        { id: "opt_c", text: "Ottawa" },
        { id: "opt_d", text: "Montreal" },
      ],
      correctOptionId: "opt_c",
    },
    {
      id: "q2",
      type: "mcq",
      subject: "Chemistry",
      text: "Which element has the chemical symbol 'Fe'?",
      pointsCorrect: 10,
      pointsIncorrect: 3,
      options: [
        { id: "opt_a", text: "Gold" },
        { id: "opt_b", text: "Iron" },
        { id: "opt_c", text: "Silver" },
        { id: "opt_d", text: "Lead" },
      ],
      correctOptionId: "opt_b",
    },
    {
      id: "q3",
      type: "numerical",
      subject: "Mathematics",
      text: "How many sides does an octagon have?",
      pointsCorrect: 15,
      pointsIncorrect: 7,
      correctAnswer: 8,
    },
    {
      id: "q4",
      type: "mcq",
      subject: "Geography",
      text: "What is the largest ocean on Earth?",
      pointsCorrect: 10,
      pointsIncorrect: 5,
      options: [
        { id: "opt_a", text: "Atlantic Ocean" },
        { id: "opt_b", text: "Indian Ocean" },
        { id: "opt_c", text: "Arctic Ocean" },
        { id: "opt_d", text: "Pacific Ocean" },
      ],
      correctOptionId: "opt_d",
    },
    {
      id: "q5",
      type: "mcq",
      subject: "History",
      text: "Who is credited with inventing the modern light bulb?",
      pointsCorrect: 10,
      pointsIncorrect: 5,
      options: [
        { id: "opt_a", text: "Nikola Tesla" },
        { id: "opt_b", text: "Alexander Graham Bell" },
        { id: "opt_c", text: "Thomas Edison" },
        { id: "opt_d", text: "Marie Curie" },
      ],
      correctOptionId: "opt_c",
    },
    {
      id: "q6",
      type: "numerical",
      subject: "History",
      text: "In what year did World War II end?",
      pointsCorrect: 20,
      pointsIncorrect: 10,
      correctAnswer: 1945,
    },
    {
      id: "q7",
      type: "mcq",
      subject: "Art",
      text: "Which artist painted 'The Starry Night'?",
      pointsCorrect: 15,
      pointsIncorrect: 5,
      options: [
        { id: "opt_a", text: "Pablo Picasso" },
        { id: "opt_b", text: "Vincent van Gogh" },
        { id: "opt_c", text: "Claude Monet" },
        { id: "opt_d", text: "Leonardo da Vinci" },
      ],
      correctOptionId: "opt_b",
    },
    {
      id: "q8",
      type: "mcq",
      subject: "Mythology",
      text: "In Greek mythology, who is the god of the sea?",
      pointsCorrect: 10,
      pointsIncorrect: 5,
      options: [
        { id: "opt_a", text: "Zeus" },
        { id: "opt_b", text: "Hades" },
        { id: "opt_c", text: "Apollo" },
        { id: "opt_d", text: "Poseidon" },
      ],
      correctOptionId: "opt_d",
    },
    {
      id: "q9",
      type: "numerical",
      subject: "Astronomy",
      text: "How many planets are currently recognized in our Solar System?",
      pointsCorrect: 10,
      pointsIncorrect: 10,
      correctAnswer: 8,
    },
    {
      id: "q10",
      type: "mcq",
      subject: "Geography",
      text: "The ancient Pyramids of Giza are located in which country?",
      pointsCorrect: 5,
      pointsIncorrect: 2,
      options: [
        { id: "opt_a", text: "Greece" },
        { id: "opt_b", text: "Egypt" },
        { id: "opt_c", text: "Sudan" },
        { id: "opt_d", text: "Turkey" },
      ],
      correctOptionId: "opt_b",
    },
    {
      id: "q11",
      type: "mcq",
      subject: "Science",
      text: "What is the most abundant gas in the Earth's atmosphere?",
      pointsCorrect: 15,
      pointsIncorrect: 8,
      options: [
        { id: "opt_a", text: "Oxygen" },
        { id: "opt_b", text: "Carbon Dioxide" },
        { id: "opt_c", text: "Nitrogen" },
        { id: "opt_d", text: "Argon" },
      ],
      correctOptionId: "opt_c",
    },
    {
      id: "q12",
      type: "numerical",
      subject: "Mathematics",
      text: "What is 25 multiplied by 4?",
      pointsCorrect: 10,
      pointsIncorrect: 5,
      correctAnswer: 100,
    },
    {
      id: "q13",
      type: "mcq",
      subject: "Literature",
      text: "Who wrote the dystopian novel '1984'?",
      pointsCorrect: 10,
      pointsIncorrect: 5,
      options: [
        { id: "opt_a", text: "Aldous Huxley" },
        { id: "opt_b", text: "George Orwell" },
        { id: "opt_c", text: "Ray Bradbury" },
        { id: "opt_d", text: "J.R.R. Tolkien" },
      ],
      correctOptionId: "opt_b",
    },
    {
      id: "q14",
      type: "mcq",
      subject: "Chemistry",
      text: "What is the chemical formula for water?",
      pointsCorrect: 5,
      pointsIncorrect: 5,
      options: [
        { id: "opt_a", text: "CO2" },
        { id: "opt_b", text: "O2" },
        { id: "opt_c", text: "H2O" },
        { id: "opt_d", text: "NaCl" },
      ],
      correctOptionId: "opt_c",
    },
    {
      id: "q15",
      type: "numerical",
      subject: "Mathematics",
      text: "What is the value of Pi (π) to two decimal places?",
      pointsCorrect: 20,
      pointsIncorrect: 5,
      correctAnswer: 3.14,
      tolerance: 0.005,
    },
  ],
};
